
CREATE TABLE public.honeypots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fake_name text NOT NULL,
  case_type text NOT NULL,
  description text NOT NULL,
  burner_phone text NOT NULL,
  phone_service text NOT NULL DEFAULT 'Burner',
  status text NOT NULL DEFAULT 'active',
  last_accessed timestamptz,
  accessed_by text,
  access_count integer NOT NULL DEFAULT 0,
  case_value text,
  cover_story text,
  planted_in text[] DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  threat_analysis text,
  access_log jsonb DEFAULT '[]',
  burner_activity jsonb DEFAULT '[]',
  CONSTRAINT honeypots_pkey PRIMARY KEY (id)
);

ALTER TABLE public.honeypots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read honeypots" ON public.honeypots
  FOR SELECT USING (auth.uid() IS NOT NULL);

CREATE POLICY "Admins can manage honeypots" ON public.honeypots
  FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

-- Seed the honeypot data
INSERT INTO public.honeypots (fake_name, case_type, description, burner_phone, phone_service, status, last_accessed, accessed_by, access_count, case_value, cover_story, planted_in, threat_analysis, access_log, burner_activity) VALUES
('Maria Delgado', 'Premises Liability, Commercial & Catastrophic', 'Around 10:15pm at a Chevron gas station — dark area, no lighting. Tripped on a raised curb while walking to pump. Right hip fractured. Two bystanders called 911 and notified cashier. Emergency hip replacement surgery, 16 days ICU, 5 days regular care.', '(408) 555-0177', 'Burner', 'triggered', now() - interval '22 minutes', 'Aisha Williams', 5, '$2,800,000', 'Premises liability case at a major gas station chain. Catastrophic injury (hip replacement, extended ICU stay) with high case value. Dark conditions and no lighting create clear liability. Designed to be irresistible to lead theft — commercial defendant, high damages, sympathetic plaintiff.', ARRAY['Litify CRM', 'Intaker Queue', 'CallRail Recent Calls'], 'Aisha Williams accessed the honeypot record at 11:02 AM, copied the phone number, and exported both the case summary and full intake record. Within 12 minutes, the burner phone received an inbound call from (510) 555-0342 — a number linked to Rivera & Associates, a competing PI firm. This confirms a pre-established referral channel. Cross-referencing shows Aisha accessed 4 other high-value premises liability cases this month that she was not assigned to.', '[{"time":"Feb 13, 11:02 AM","action":"Viewed full case record including contact details","user":"Aisha Williams","ip":"192.168.1.47","device":"Chrome / Windows — Office Workstation","type":"access"},{"time":"Feb 13, 11:03 AM","action":"Copied phone number to clipboard","user":"Aisha Williams","ip":"192.168.1.47","device":"Chrome / Windows — Office Workstation","type":"access"},{"time":"Feb 13, 11:05 AM","action":"Exported case summary to PDF","user":"Aisha Williams","ip":"192.168.1.47","device":"Chrome / Windows — Office Workstation","type":"export"},{"time":"Feb 13, 11:09 AM","action":"Downloaded full intake record with medical details","user":"Aisha Williams","ip":"192.168.1.47","device":"Chrome / Windows — Office Workstation","type":"export"},{"time":"Feb 13, 11:14 AM","action":"Burner phone received incoming call from (510) 555-0342","user":"Unknown External","ip":"N/A","device":"N/A","type":"call"},{"time":"Feb 13, 11:14 AM","action":"🚨 SECURITY ALERT: Honeypot phone contacted — insider confirmed","user":"System","ip":"N/A","device":"N/A","type":"alert"}]', '[{"type":"call","from":"(510) 555-0342","time":"Feb 13, 11:14 AM","content":"Incoming call — 18 seconds. Caller asked for Maria regarding her gas station fall. Voicemail left."},{"type":"voicemail","from":"(510) 555-0342","time":"Feb 13, 11:14 AM","content":"Hi Maria, this is Tony from Rivera & Associates. I understand you had a serious fall at a gas station. We specialize in premises liability and would love to help. Please call me back."}]'),
('Jorge Reyes', 'Premises Liability, Substantial Injury Major', 'Bicyclist struck a 5-inch raised cement obstruction on sidewalk — unfinished construction, no warning signs. Right leg broken, surgery on right knee. Hospitalized 8 days, currently in rehab facility. Witnesses available.', '(714) 555-0263', 'TextMe', 'active', NULL, NULL, 0, '$1,400,000', 'Sidewalk defect premises liability — city or construction company defendant. Unfinished cement hazard with no signage creates strong liability. Knee surgery plus extended rehab drives case value. Planted as a recent intake with photos pending.', ARRAY['Litify CRM', 'Intaker Queue'], NULL, '[]', '[]'),
('Linda Tran', 'Auto MVA, Death', 'Decedent was traveling on the 10 freeway, rear-ended by a commercial semi-truck at highway speed. Killed on scene. CHP report confirms truck driver at fault. Multiple witnesses.', '(626) 555-0198', 'TextNow', 'active', NULL, NULL, 0, '$5,200,000', 'Wrongful death auto case with commercial truck involvement. Highest-value honeypot — $5.2M estimated. Death cases with commercial defendants are the most sought-after by lead buyers. Planted across 3 systems for maximum detection.', ARRAY['Litify CRM', 'Internal Reports', 'CallRail Recent Calls'], NULL, '[]', '[]'),
('Sandra Okafor', 'Auto MVA, Death Commercial', 'Vehicle had a known wiring recall (repair appointment was scheduled). Car lost control — computer system shut off, auto-stop failed, airbags did not deploy. Driver struck a wall and was killed. Manufacturer defect suspected.', '(818) 555-0144', 'Burner', 'active', NULL, NULL, 0, '$6,500,000', 'Product liability / wrongful death hybrid — vehicle recall with documented failure. Airbag non-deployment plus manufacturer defect creates massive case value. The recall appointment detail adds urgency and sympathy. Extremely attractive to competing firms.', ARRAY['Litify CRM', 'Intaker Queue'], NULL, '[]', '[]'),
('Rosa Gutierrez', 'Auto MVA, Catastrophic', 'Traveling straight on a main boulevard when defendant turned left into a parking lot, causing head-on collision. Kidney surgery required, hospitalized since incident. Expected 2+ more weeks in rehabilitation. Will be wheelchair-bound for extended period.', '(562) 555-0211', 'TextMe', 'active', NULL, NULL, 0, '$3,100,000', 'Catastrophic auto MVA with clear liability (defendant turned left into oncoming traffic). Kidney surgery, extended hospitalization, and wheelchair-bound recovery. Planted across 3 systems with high urgency indicators.', ARRAY['Litify CRM', 'CallRail Recent Calls', 'Intaker Queue'], NULL, '[]', '[]'),
('Amara Jenkins', 'Dog Bite, Catastrophic Commercial', 'Minor child bitten on face while in foster care — chin, left cheek puncture wounds, lip torn in half, permanent scarring. Dog had prior bite history including severing a finger. Dog was euthanized. Mother was never notified of incident.', '(323) 555-0199', 'Burner', 'active', NULL, NULL, 0, '$2,200,000', 'Child victim dog bite in foster care — extremely sympathetic case with institutional negligence angle. Prior bite history on the dog creates clear liability. Facial scarring on a minor drives high damages. Emotional case type makes it a prime target for lead theft.', ARRAY['Litify CRM', 'Intaker Queue'], NULL, '[]', '[]'),
('Kevin Nakamura', 'Wage & Hour', 'Night auditor / front desk at a major hotel chain. Never provided meal or rest breaks during overnight shifts. Systematic violations across multiple pay periods.', '(408) 555-0288', 'TextNow', 'dormant', now() - interval '45 days', NULL, 0, '$180,000', 'Wage & hour case against a hotel chain — lower value but tests whether agents are also skimming employment cases. Night shift worker denied breaks is a common, credible scenario. Dormant — may need timestamp refresh.', ARRAY['Litify CRM'], NULL, '[]', '[]'),
('Derek Lawson', 'Wage & Hour', 'Car salesman at a dealership. Required to attend unpaid pre-shift meetings, purchased work laptop with own funds, consistently interrupted during meal breaks.', '(415) 555-0177', 'TextMe', 'dormant', now() - interval '38 days', NULL, 0, '$220,000', 'Employment case against an auto dealership — multiple wage violations including off-the-clock work and expense reimbursement. Lower priority honeypot for detecting employment-case-specific theft patterns. Dormant — needs refresh.', ARRAY['Litify CRM'], NULL, '[]', '[]');
